name: CI pipeline
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: microsoft
          java-version: '11'
          cache: 'maven'
      - name: running tests
        run: |
          ls
          mvn test

      - name: build package
        run: mvn -q package -Dmaven.test.skip=true

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: target/**

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: target
      - name: show content of target
        run: ls target




